package com.kc.walle.station.engine.daemon.common;

public enum ErrorCode {

	ERROR_INTERNAL("ERROR_INTERNAL", "内部错误"),
	LOGIN_INFO_EMTPY("LOGIN_INFO_EMTPY", "登录信息为空"),
	LOGIN_ACCOUNT_EMTPY("LOGIN_ACCOUNT_EMTPY", "登录账号为空"),
	LOGIN_PASSWORD_EMTPY("LOGIN_PASSWORD_EMTPY", "登录密码为空"),
	LOGIN_ACCOUNT_NOT_EXIST("LOGIN_ACCOUNT_NOT_EXIST", "登录账号(%s)不存在"),
	LOGIN_PASSWORD_ERROR("LOGIN_PASSWORD_ERROR", "登录密码不正确"),
	CUSTOMER_EMPTY("CUSTOMER_EMPTY", "系统未配置客户信息"),
	
	BUCKET_TYPE_EMPTY("BUCKET_TYPE_EMPTY", "系统未配置货架类型"),
	BUCKET_SLOT_TYPE_EMPTY("BUCKET_SLOT_TYPE_EMPTY", "系统未配置货位类型"),
	
	SCAN_STATION_PARAM_EMPTY("SCAN_STATION_PARAM_EMPTY", "未扫描到工作站号，请重新扫描"),
	SCAN_STATION_NOT_EXIST("SCAN_STATION_NOT_EXIST", "扫描的工作站(%s)不存在"),
	SCAN_STATION_NOT_OFFLINE_REPLENISH_STATION("SCAN_STATION_NOT_OFFLINE_REPLENISH_STATION", "扫描的工作站(%s)不是离线补货站"),
	SCAN_STATION_UN_ENABLED("SCAN_STATION_UN_ENABLED", "扫描的工作站(%s)未启用"),
	
	STATION_DISPATCHED_BUCKETS("STATION_DISPATCHED_BUCKETS", "工作站(%s)已调度过货架"),
	STATION_NO_DISPATCH_BUCKETS("STATION_NO_DISPATCH_BUCKETS", "工作站(%s)没有正在执行的调度货架任务"),
	
	DISPATCH_BUCKET_PARAM_EMPTY("DISPATCH_BUCKET_PARAM_EMPTY", "调度货架参数为空"),
	DISPATCH_BUCKET_CUSTOMER_EMPTY("DISPATCH_BUCKET_CUSTOMER_EMPTY", "调度货架客户参数为空"),
	DISPATCH_BUCKET_STATION_EMPTY("DISPATCH_BUCKET_STATION_EMPTY", "调度货架离线站参数为空"),
	DISPATCH_BUCKET_ERROR("DISPATCH_BUCKET_ERROR", "调度货架异常"),
	FINISH_DISPATCH_BUCKET_STATION_EMPTY("FINISH_DISPATCH_BUCKET_STATION_EMPTY", "结束调度货架离线站参数为空"),
	BUCKET_SLOT_PARAM_EMPTY("BUCKET_SLOT_PARAM_EMPTY", "传入货位参数为空"),
	BUCKET_SLOT_NOT_EXIST("BUCKET_SLOT_NOT_EXIST", "货位(%s)不存在"),
	BUCKET_NOT_BUCKET_EXIST("BUCKET_NOT_BUCKET_EXIST", "货位(%s)对应的货架不存在"),
	BUCKET_SLOT_WAYPOINT_NOT_EXIST("BUCKET_SLOT_WAYPOINT_NOT_EXIST", "货位(%s)对应的点位不存在"),
	BUCKET_SLOT_NOT_OFFLINE("BUCKET_SLOT_NOT_OFFLINE", "货位(%s)对应的货架不在离线点"),
	RELEASE_BUCKET_REQUEST_ERROR("RELEASE_BUCKET_REQUEST_ERROR", ""),
	DISPATCH_BUCKET_NO_BUCKETS("DISPATCH_BUCKET_NO_BUCKETS", "没有合适的货架"),
	
	SCAN_BILL_BOX_SCANCODE_EMPTY("SCAN_BILL_BOX_SCANCODE_EMPTY", "扫描单据/LPN扫描内容为空"),
	SCAN_BILL_BOX_CUSTOMERID_EMPTY("SCAN_BILL_BOX_CUSTOMERID_EMPTY", "扫描单据/LPN客户为空为空"),
	SCAN_BILL_BOX_ERROR("SCAN_BILL_BOX_ERROR", "扫描单据/LPN异常"),
	
	SCAN_SKU_CODE_EMPTY("SCAN_SKU_CODE_EMPTY", "扫描商品传入的条码为空"),
	SCAN_SKU_BILLBOX_EMPTY("SCAN_SKU_BILLBOX_EMPTY", "扫描商品传入的单据/LPN为空"),
	SCAN_SKU_BILLBOX_TYPE_ERROR("SCAN_SKU_BILLBOX_TYPE_ERROR", "扫描商品传入的单据/LPN分类异常"),
	SCAN_SKU_CUSTOMER_EMPTY("SCAN_SKU_CUSTOMER_EMPTY", "扫描商品传入的客户为空"),
	SCAN_SKU_NOT_EXIST("SCAN_SKU_NOT_EXIST", "扫描的商品(%s)不存在"),
	SCAN_SKU_ERROR("SCAN_SKU_ERROR", "扫描商品异常"),
	
	BUCKET_SLOT_UNBIND_STATION("BUCKET_SLOT_UNBIND_STATION", "货位(%s)未绑定离线站"),
	BUCKET_SLOT_UNBIND_STATION_MORE_THAN_ONE("BUCKET_SLOT_UNBIND_STATION_MORE_THAN_ONE", "货位(%s)绑定了多个离线站"),
	BUCKET_SLOT_UNBIND_STATION_NOT_OFFLINE_REPLENISH_STATION("BUCKET_SLOT_UNBIND_STATION_NOT_OFFLINE_REPLENISH_STATION", "货位(%s)绑定了的工作站(%s)不是离线补货站站"),
	
	SHELVE_PARAM_EMPTY("SHELVE_PARAM_EMPTY", "上架传入参数为空"),
	SHELVE_SKU_PARAM_EMPTY("SHELVE_SKU_PARAM_EMPTY", "上架传入商品参数为空"),
	SHELVE_BILLBOX_PARAM_EMPTY("SHELVE_BILLBOX_PARAM_EMPTY", "上架传入单据或箱号参数为空"),
	SHELVE_BILLBOX_TYPE_PARAM_ERROR("SHELVE_BILLBOX_TYPE_PARAM_ERROR", "上架传入的单据/LPN分类异常"),
	SHELVE_CUSTOMERID_PARAM_ERROR("SHELVE_CUSTOMERID_PARAM_ERROR", "上架传入的客户为空"),
	SHELVE_SKU_BUCKET_ATTRIBUTE_INCONFORMITY("SHELVE_SKU_BUCKET_ATTRIBUTE_INCONFORMITY", "商品(%s)批次(%s)与货架(%s)属性不一致"),
	SHELVE_ERROR("SHELVE_ERROR", "上架出错"),
	;
	
    private String code;

    private String message;

    ErrorCode(String code, String message) {
		this.code = code;
		this.message = message;
    }

	public String getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

	
    
}
